[package]
name = "manalimit-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
manalimit-core = { path = "../core", default-features = true }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1"
wee_alloc = { version = "0.4", optional = true }
web-sys = { version = "0.3", features = ["console"] }
getrandom = { version = "0.2", features = ["js"] }

[features]
default = ["wee_alloc"]

[profile.release]
opt-level = "s"
lto = true